# Copyright (C) 2026 Jeremy Jeanne <jyjeanne@gmail.com>
#
# This file is part of GalaxyWizard.
#
# GalaxyWizard is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

"""Generate UML diagrams for the GalaxyWizard codebase.

Runs pyreverse (bundled with pylint) over the source tree, converts the
result to Mermaid, and assembles ``doc/architecture.md`` so the diagrams
render directly in the GitHub web UI. The raw ``.mmd`` sources are kept
in ``doc/uml/`` for reuse in other tools.

Usage::

    poetry run galaxywizard-uml
    # or
    python generate_uml.py
"""

import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
SRC_DIR = REPO_ROOT / "src"
DOC_DIR = REPO_ROOT / "doc"
UML_DIR = DOC_DIR / "uml"
ARCHITECTURE_MD = DOC_DIR / "architecture.md"

# Top-level modules that form the application core (src/data and src/test
# are excluded: data files are exec()'d DSL scripts, test is legacy
# scaffolding — see the matching excludes in pyproject.toml).
CORE_MODULES = [
    "constants.py",
    "fsm.py",
    "log.py",
    "main.py",
    "resources.py",
    "sound.py",
    "translate.py",
    "twistedmain.py",
    "util.py",
]

ALL_TARGETS = ["ai", "engine", "gui"] + CORE_MODULES

# (project name, pyreverse targets) — one class diagram per entry.
CLASS_DIAGRAMS = [
    ("engine", ["engine"]),
    ("gui", ["gui"]),
    ("ai", ["ai"]),
    ("core", CORE_MODULES),
]

SECTIONS = [
    (
        "Module dependencies",
        "packages_overview.mmd",
        "Import relationships between the main packages and modules. "
        "An arrow `A --> B` means *A imports B*.",
    ),
    (
        "Engine (`src/engine`)",
        "classes_engine.mmd",
        "Core game logic: battles, maps, units, abilities, effects, "
        "equipment and scenario handling.",
    ),
    (
        "GUI (`src/gui`)",
        "classes_gui.mmd",
        "OpenGL rendering, camera, input handling, sprites and the "
        "map editor interface.",
    ),
    (
        "AI (`src/ai`)",
        "classes_ai.mmd",
        "Computer-controlled unit behavior.",
    ),
    (
        "Core modules (`src/*.py`)",
        "classes_core.mmd",
        "Application entry points, resource loading, sound, "
        "localization and shared utilities.",
    ),
]

HEADER = """\
# GalaxyWizard Architecture

<!-- This file is AUTO-GENERATED by generate_uml.py — do not edit by hand.
     Regenerate with: poetry run galaxywizard-uml -->

UML diagrams of the GalaxyWizard codebase, generated with
[pyreverse](https://pylint.readthedocs.io/en/latest/additional_tools/pyreverse/index.html)
and rendered by GitHub's built-in [Mermaid](https://mermaid.js.org/) support.
The raw Mermaid sources live in [`doc/uml/`](uml/).

To regenerate after changing the code:

```bash
poetry run galaxywizard-uml
```
"""


def run_pyreverse(project: str, targets: list[str], out_dir: Path) -> None:
    """Run pyreverse for *targets*, writing Mermaid files into *out_dir*.

    Invoked through ``python -c`` so it works without the pyreverse
    console script on PATH, with src/ as both cwd and source root so
    that the project's top-level imports (``from engine import ...``)
    resolve.
    """
    cmd = [
        sys.executable,
        "-c",
        "import sys; from pylint import run_pyreverse; run_pyreverse(sys.argv[1:])",
        "--output=mmd",
        "--source-roots=.",
        f"--project={project}",
        f"--output-directory={out_dir}",
        *targets,
    ]
    result = subprocess.run(cmd, cwd=SRC_DIR, capture_output=True, text=True)
    if result.returncode != 0:
        sys.stderr.write(result.stdout + result.stderr)
        raise SystemExit(f"pyreverse failed for project '{project}'")
    summary = result.stdout.strip().splitlines()
    if summary:
        print(f"  {project}: {summary[-1]}")


def generate_diagrams() -> None:
    """Generate all .mmd files into doc/uml/."""
    UML_DIR.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)

        print("Generating package overview diagram...")
        run_pyreverse("overview", ALL_TARGETS, tmp_dir)
        for name, targets in CLASS_DIAGRAMS:
            print(f"Generating class diagram for {name}...")
            run_pyreverse(name, targets, tmp_dir)

        # Keep only the diagrams referenced by architecture.md.
        wanted = [filename for _, filename, _ in SECTIONS]
        for old in UML_DIR.glob("*.mmd"):
            if old.name not in wanted:
                old.unlink()
        for filename in wanted:
            (UML_DIR / filename).write_text(
                (tmp_dir / filename).read_text(encoding="utf-8"), encoding="utf-8"
            )


def build_architecture_md() -> None:
    """Assemble doc/architecture.md from the generated .mmd files."""
    parts = [HEADER]
    for title, filename, description in SECTIONS:
        mermaid = (UML_DIR / filename).read_text(encoding="utf-8").strip()
        parts.append(
            f"\n## {title}\n\n{description}\n\n```mermaid\n{mermaid}\n```\n"
        )
    ARCHITECTURE_MD.write_text("".join(parts), encoding="utf-8")
    print(f"Wrote {ARCHITECTURE_MD.relative_to(REPO_ROOT)}")


def main() -> None:
    generate_diagrams()
    build_architecture_md()
    print("Done. View doc/architecture.md on GitHub to see the rendered diagrams.")


if __name__ == "__main__":
    main()
