[tool.poetry]
name = "galaxywizard"
version = "0.1.0"
description = "GalaxyWizard is an open-source tactical RPG written with python language"
authors = ["jeremy_jeanne <jyjeanne@gmail.com>"]
license = "GPL-2.0 license"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^1.26.4"
PyOpenGL = "^3.1.7"
pygame = "^2.5.2"
Twisted = "^24.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
